server:
  port: 9090

spring.zipkin:
  base-url: http://localhost:9411

spring.application:
  name: CUSTOMER-SERVICE

spring.jpa:
  database: POSTGRESQL
  hibernate:
    ddl-auto: update
    show-sql: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.10.55:5432/customers
    username: postgres
    password: Welcome


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost