server:
  port: 9091

spring.application:
  name: FRAUD-SERVICE

spring.jpa:
  database: POSTGRESQL
  hibernate:
    ddl-auto: update
    show-sql: true

spring.zipkin:
  base-url: http://localhost:9411

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.60.132.163:5432/frauds
    username: postgres
    password: Welcome

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost